class EngineSettings:
        def __init__(self, 
                    engine_id="text-curie-01",
                    search_model_id="text-curie-01",
                    prompt='<|endoftext|>',
                    input='',
                    instruction=None,
                    query='',
                    documents=None,
                    file=None,
                    labels=None, 
                    suffix=None, max_tokens=16, 
                    temperature=1, 
                    top_p=1, 
                    n=1,
                    max_rerank=200,
                    return_metadata=False, 
                    stream=False,
                    logprobs=None,
                    echo=False,
                    stop=None,
                    presence_penalty=0,
                    frequency_penalty=0,
                    best_of=1,
                    logit_bias=None,
                    user=None):
            self.engine_id = engine_id
            self.search_model_id = search_model_id
            self.prompt = prompt
            self.input = input
            self.instruction = instruction
            self.query = query
            self.documents = documents
            self.file = file
            self.labels = labels
            self.suffix = suffix
            self.max_tokens = max_tokens
            self.temperature = temperature
            self.top_p = top_p
            self.max_rerank = max_rerank
            self.return_metadata = return_metadata
            self.n = n
            self.stream = stream
            self.logprobs = logprobs
            self.echo = echo
            self.stop = stop
            self.presence_penalty = presence_penalty
            self.frequency_penalty = frequency_penalty
            self.best_of = best_of
            self.logit_bias = logit_bias
            self.user = user